# Default values for users-otus-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

fullnameOverride: "users-otus"

image: jawello/users-otus:0.0.1

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: arch.homework
      paths:
        path: /users

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: otus
  postgresqlDatabase: postgres
  service:
    port: "5432"
  metrics:
    enabled: false
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s