name: Docker Push Release
on:
  push:
    branches:
      - release/v*
jobs:
  docker-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION_USERS_OTUS::${GITHUB_REF#refs/heads/release/v}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          BUILD_PATH: "src"
          DOCKERFILE: "src/Dockerfile"
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/users-otus
          TAG_NAME: ${{ steps.get_version.outputs.VERSION_USERS_OTUS }}